periodic_table = {
    1: {'symbol': 'H', 'name': 'Hydrogen', 'atomic_number': 1, 'electrons': 1, 'protons': 1, 'atomic_weight': 1.008},
    2: {'symbol': 'He', 'name': 'Helium', 'atomic_number': 2, 'electrons': 2, 'protons': 2, 'atomic_weight': 4.0026},
    3: {'symbol': 'Li', 'name': 'Lithium', 'atomic_number': 3, 'electrons': 3, 'protons': 3, 'atomic_weight': 6.94},
    4: {'symbol': 'Be', 'name': 'Beryllium', 'atomic_number': 4, 'electrons': 4, 'protons': 4, 'atomic_weight': 9.0122},
    5: {'symbol': 'B', 'name': 'Boron', 'atomic_number': 5, 'electrons': 5, 'protons': 5, 'atomic_weight': 10.81},
    6: {'symbol': 'C', 'name': 'Carbon', 'atomic_number': 6, 'electrons': 6, 'protons': 6, 'atomic_weight': 12.011},
    7: {'symbol': 'N', 'name': 'Nitrogen', 'atomic_number': 7, 'electrons': 7, 'protons': 7, 'atomic_weight': 14.007},
    8: {'symbol': 'O', 'name': 'Oxygen', 'atomic_number': 8, 'electrons': 8, 'protons': 8, 'atomic_weight': 15.999},
    9: {'symbol': 'F', 'name': 'Fluorine', 'atomic_number': 9, 'electrons': 9, 'protons': 9, 'atomic_weight': 18.998},
    10: {'symbol': 'Ne', 'name': 'Neon', 'atomic_number': 10, 'electrons': 10, 'protons': 10, 'atomic_weight': 20.180},
    11: {'symbol': 'Na', 'name': 'Sodium', 'atomic_number': 11, 'electrons': 11, 'protons': 11, 'atomic_weight': 22.990},
    12: {'symbol': 'Mg', 'name': 'Magnesium', 'atomic_number': 12, 'electrons': 12, 'protons': 12, 'atomic_weight': 24.305},
    13: {'symbol': 'Al', 'name': 'Aluminum', 'atomic_number': 13, 'electrons': 13, 'protons': 13, 'atomic_weight': 26.982},
    14: {'symbol': 'Si', 'name': 'Silicon', 'atomic_number': 14, 'electrons': 14, 'protons': 14, 'atomic_weight': 28.085},
    15: {'symbol': 'P', 'name': 'Phosphorus', 'atomic_number': 15, 'electrons': 15, 'protons': 15, 'atomic_weight': 30.974},
    16: {'symbol': 'S', 'name': 'Sulfur', 'atomic_number': 16, 'electrons': 16, 'protons': 16, 'atomic_weight': 32.06},
    17: {'symbol': 'Cl', 'name': 'Chlorine', 'atomic_number': 17, 'electrons': 17, 'protons': 17, 'atomic_weight': 35.45},
    18: {'symbol': 'Ar', 'name': 'Argon', 'atomic_number': 18, 'electrons': 18, 'protons': 18, 'atomic_weight': 39.948},
    19: {'symbol': 'K', 'name': 'Potassium', 'atomic_number': 19, 'electrons': 19, 'protons': 19, 'atomic_weight': 39.098},
    20: {'symbol': 'Ca', 'name': 'Calcium', 'atomic_number': 20, 'electrons': 20, 'protons': 20,'atomic_weight': 40.078},
    21: {'symbol': 'Sc', 'name': 'Scandium', 'atomic_number': 21, 'electrons': 21, 'protons': 21,'atomic_weight': 44.956},
    22: {'symbol': 'Ti', 'name': 'Titanium', 'atomic_number': 22, 'electrons': 22, 'protons': 22,'atomic_weight': 47.867},
    23: {'symbol': 'V', 'name': 'Vanadium', 'atomic_number': 23, 'electrons': 23, 'protons': 23,'atomic_weight': 50.942},
    24: {'symbol': 'Cr', 'name': 'Chromium', 'atomic_number': 24, 'electrons': 24, 'protons': 24,'atomic_weight': 51.996},
    25: {'symbol': 'Mn', 'name': 'Manganese', 'atomic_number': 25, 'electrons': 25, 'protons': 25, 'atomic_weight': 54.938},
    26: {'symbol': 'Fe', 'name': 'Iron', 'atomic_number': 26, 'electrons': 26, 'protons': 26, 'atomic_weight': 55.845},
    27: {'symbol': 'Co', 'name': 'Cobalt', 'atomic_number': 27, 'electrons': 27, 'protons': 27, 'atomic_weight': 58.933},
    28: {'symbol': 'Ni', 'name': 'Nickel', 'atomic_number': 28, 'electrons': 28, 'protons': 28, 'atomic_weight': 58.693},
    29: {'symbol': 'Cu', 'name': 'Copper', 'atomic_number': 29, 'electrons': 29, 'protons': 29,'atomic_weight': 63.546},
    30: {'symbol': 'Zn', 'name': 'Zinc', 'atomic_number': 30, 'electrons': 30, 'protons': 30, 'atomic_weight': 65.38},
    31: {'symbol': 'Ga', 'name': 'Gallium', 'atomic_number': 31, 'electrons': 31, 'protons': 31, 'atomic_weight': 69.723},
    32: {'symbol': 'Ge', 'name': 'Germanium', 'atomic_number': 32, 'electrons': 32, 'protons': 32,'atomic_weight': 72.63},
    33: {'symbol': 'As', 'name': 'Arsenic', 'atomic_number': 33, 'electrons': 33, 'protons': 33,'atomic_weight': 74.922},
    34: {'symbol': 'Se', 'name': 'Selenium', 'atomic_number': 34, 'electrons': 34, 'protons': 34, 'atomic_weight': 78.971},
    35: {'symbol': 'Br', 'name': 'Bromine', 'atomic_number': 35, 'electrons': 35, 'protons': 35,'atomic_weight': 79.904},
    36: {'symbol': 'Kr', 'name': 'Krypton', 'atomic_number': 36, 'electrons': 36, 'protons': 36,'atomic_weight': 83.798},
    37: {'symbol': 'Rb', 'name': 'Rubidium', 'atomic_number': 37, 'electrons': 37, 'protons': 37, 'atomic_weight': 85.468},
    38: {'symbol': 'Sr', 'name': 'Strontium', 'atomic_number': 38, 'electrons': 38, 'protons': 38, 'atomic_weight': 87.62},
    39: {'symbol': 'Y', 'name': 'Yttrium', 'atomic_number': 39, 'electrons': 39, 'protons': 39, 'atomic_weight': 88.906},
    40: {'symbol': 'Zr', 'name': 'Zirconium', 'atomic_number': 40, 'electrons': 40, 'protons': 40, 'atomic_weight': 91.224},
    41: {'symbol': 'Nb', 'name': 'Niobium', 'atomic_number': 41, 'electrons': 41, 'protons': 41, 'atomic_weight': 92.906},
    42: {'symbol': 'Mo', 'name': 'Molybdenum', 'atomic_number': 42, 'electrons': 42, 'protons': 42, 'atomic_weight': 95.95},
    43: {'symbol': 'Tc', 'name': 'Technetium', 'atomic_number': 43, 'electrons': 43, 'protons': 43, 'atomic_weight': 98},
    44: {'symbol': 'Ru', 'name': 'Ruthenium', 'atomic_number': 44, 'electrons': 44, 'protons': 44, 'atomic_weight': 101.07},
    45: {'symbol': 'Rh', 'name': 'Rhodium', 'atomic_number': 45, 'electrons': 45, 'protons': 45, 'atomic_weight': 102.91},
    46: {'symbol': 'Pd', 'name': 'Palladium', 'atomic_number': 46, 'electrons': 46, 'protons': 46, 'atomic_weight': 106.42},
    47: {'symbol': 'Ag', 'name': 'Silver', 'atomic_number': 47, 'electrons': 47, 'protons': 47, 'atomic_weight': 107.87},
    48: {'symbol': 'Cd', 'name': 'Cadmium', 'atomic_number': 48, 'electrons': 48, 'protons': 48, 'atomic_weight': 112.41},
    49: {'symbol': 'In', 'name': 'Indium', 'atomic_number': 49, 'electrons': 49, 'protons': 49, 'atomic_weight': 114.82},
    50: {'symbol': 'Sn', 'name': 'Tin', 'atomic_number': 50, 'electrons': 50, 'protons': 50, 'atomic_weight': 118.71},
    51: {'symbol': 'Sb', 'name': 'Antimony', 'atomic_number': 51, 'electrons': 51, 'protons': 51, 'atomic_weight': 121.76},
    52: {'symbol': 'Te', 'name': 'Tellurium', 'atomic_number': 52, 'electrons': 52, 'protons': 52, 'atomic_weight': 127.6},
    53: {'symbol': 'I', 'name': 'Iodine', 'atomic_number': 53, 'electrons': 53, 'protons': 53, 'atomic_weight': 126.9},
    54: {'symbol': 'Xe', 'name': 'Xenon', 'atomic_number': 54, 'electrons': 54, 'protons': 54, 'atomic_weight': 131.29},
    55: {'symbol': 'Cs', 'name': 'Cesium', 'atomic_number': 55, 'electrons': 55, 'protons': 55, 'atomic_weight': 132.91},
    56: {'symbol': 'Ba', 'name': 'Barium', 'atomic_number': 56, 'electrons': 56, 'protons': 56, 'atomic_weight': 137.33},
    57: {'symbol': 'La', 'name': 'Lanthanum', 'atomic_number': 57, 'electrons': 57, 'protons': 57, 'atomic_weight': 138.91},
    58: {'symbol': 'Ce', 'name': 'Cerium', 'atomic_number': 58, 'electrons': 58, 'protons': 58, 'atomic_weight': 140.12},
    59: {'symbol': 'Pr', 'name': 'Praseodymium', 'atomic_number': 59, 'electrons': 59, 'protons': 59, 'atomic_weight': 140.91},
    60: {'symbol': 'Nd', 'name': 'Neodymium', 'atomic_number': 60, 'electrons': 60, 'protons': 60, 'atomic_weight': 144.24},
    61: {'symbol': 'Pm', 'name': 'Promethium', 'atomic_number': 61, 'electrons': 61, 'protons': 61, 'atomic_weight': 145},
    62: {'symbol': 'Sm', 'name': 'Samarium', 'atomic_number': 62, 'electrons': 62, 'protons': 62, 'atomic_weight': 150.36},
    63: {'symbol': 'Eu', 'name': 'Europium', 'atomic_number': 63, 'electrons': 63, 'protons': 63, 'atomic_weight': 151.96},
    64: {'symbol': 'Gd', 'name': 'Gadolinium', 'atomic_number': 64, 'electrons': 64, 'protons': 64, 'atomic_weight': 157.25},
    65: {'symbol': 'Tb', 'name': 'Terbium', 'atomic_number': 65, 'electrons': 65, 'protons': 65, 'atomic_weight': 158.93},
    66: {'symbol': 'Dy', 'name': 'Dysprosium', 'atomic_number': 66, 'electrons': 66, 'protons': 66, 'atomic_weight': 162.5},
    67: {'symbol': 'Ho', 'name': 'Holmium', 'atomic_number': 67, 'electrons': 67, 'protons': 67, 'atomic_weight': 164.93},
    68: {'symbol': 'Er', 'name': 'Erbium', 'atomic_number': 68, 'electrons': 68, 'protons': 68, 'atomic_weight': 167.26},
    69: {'symbol': 'Tm', 'name': 'Thulium', 'atomic_number': 69, 'electrons': 69, 'protons': 69, 'atomic_weight': 168.93},
    70: {'symbol': 'Yb', 'name': 'Ytterbium', 'atomic_number': 70, 'electrons': 70, 'protons': 70, 'atomic_weight': 173.05},
    71: {'symbol': 'Lu', 'name': 'Lutetium', 'atomic_number': 71, 'electrons': 71, 'protons': 71, 'atomic_weight': 174.97},
    72: {'symbol': 'Hf', 'name': 'Hafnium', 'atomic_number': 72, 'electrons': 72, 'protons': 72, 'atomic_weight': 178.49},
    73: {'symbol': 'Ta', 'name': 'Tantalum', 'atomic_number': 73, 'electrons': 73, 'protons': 73, 'atomic_weight': 180.95},
    74: {'symbol': 'W', 'name': 'Tungsten', 'atomic_number': 74, 'electrons': 74, 'protons': 74, 'atomic_weight': 183.84},
    75: {'symbol': 'Re', 'name': 'Rhenium', 'atomic_number': 75, 'electrons': 75, 'protons': 75, 'atomic_weight': 186.21},
    76: {'symbol': 'Os', 'name': 'Osmium', 'atomic_number': 76, 'electrons': 76, 'protons': 76, 'atomic_weight': 190.23},
    77: {'symbol': 'Ir', 'name': 'Iridium', 'atomic_number': 77, 'electrons': 77, 'protons': 77, 'atomic_weight': 192.22},
    78: {'symbol': 'Pt', 'name': 'Platinum', 'atomic_number': 78, 'electrons': 78, 'protons': 78, 'atomic_weight': 195.08},
    79: {'symbol': 'Au', 'name': 'Gold', 'atomic_number': 79, 'electrons': 79, 'protons': 79, 'atomic_weight': 196.97},
    80: {'symbol': 'Hg', 'name': 'Mercury', 'atomic_number': 80, 'electrons': 80, 'protons': 80, 'atomic_weight': 200.59},
    81: {'symbol': 'Tl', 'name': 'Thallium', 'atomic_number': 81, 'electrons': 81, 'protons': 81, 'atomic_weight': 204.38},
    82: {'symbol': 'Pb', 'name': 'Lead', 'atomic_number': 82, 'electrons': 82, 'protons': 82, 'atomic_weight': 207.2},
    83: {'symbol': 'Bi', 'name': 'Bismuth', 'atomic_number': 83, 'electrons': 83, 'protons': 83, 'atomic_weight': 208.98},
    84: {'symbol': 'Po', 'name': 'Polonium', 'atomic_number': 84, 'electrons': 84, 'protons': 84, 'atomic_weight': 209},
    85: {'symbol': 'At', 'name': 'Astatine', 'atomic_number': 85, 'electrons': 85, 'protons': 85, 'atomic_weight': 210},
    86: {'symbol': 'Rn', 'name': 'Radon', 'atomic_number': 86, 'electrons': 86, 'protons': 86, 'atomic_weight': 222},
    87: {'symbol': 'Fr', 'name': 'Francium', 'atomic_number': 87, 'electrons': 87, 'protons': 87, 'atomic_weight': None},
    88: {'symbol': 'Ra', 'name': 'Radium', 'atomic_number': 88, 'electrons': 88, 'protons': 88, 'atomic_weight': None},
    89: {'symbol': 'Ac', 'name': 'Actinium', 'atomic_number': 89, 'electrons': 89, 'protons': 89, 'atomic_weight': None},
    90: {'symbol': 'Th', 'name': 'Thorium', 'atomic_number': 90, 'electrons': 90, 'protons': 90, 'atomic_weight': 232.04},
    91: {'symbol': 'Pa', 'name': 'Protactinium', 'atomic_number': 91, 'electrons': 91, 'protons': 91, 'atomic_weight': 231.04},
    92: {'symbol': 'U', 'name': 'Uranium', 'atomic_number': 92, 'electrons': 92, 'protons': 92, 'atomic_weight': 238.03},
    93: {'symbol': 'Np', 'name': 'Neptunium', 'atomic_number': 93, 'electrons': 93, 'protons': 93, 'atomic_weight': 237},
    94: {'symbol': 'Pu', 'name': 'Plutonium', 'atomic_number': 94, 'electrons': 94, 'protons': 94, 'atomic_weight': 244},
    95: {'symbol': 'Am', 'name': 'Americium', 'atomic_number': 95, 'electrons': 95, 'protons': 95, 'atomic_weight': 243},
    96: {'symbol': 'Cm', 'name': 'Curium', 'atomic_number': 96, 'electrons': 96, 'protons': 96, 'atomic_weight': 247},
    97: {'symbol': 'Bk', 'name': 'Berkelium', 'atomic_number': 97, 'electrons': 97, 'protons': 97, 'atomic_weight': 247},
    98: {'symbol': 'Cf', 'name': 'Californium', 'atomic_number': 98, 'electrons': 98, 'protons': 98, 'atomic_weight': 251},
    99: {'symbol': 'Es', 'name': 'Einsteinium', 'atomic_number': 99, 'electrons': 99, 'protons': 99, 'atomic_weight': 252},
    100: {'symbol': 'Fm', 'name': 'Fermium', 'atomic_number': 100, 'electrons': 100, 'protons': 100, 'atomic_weight': 257},
    101: {'symbol': 'Md', 'name': 'Mendelevium', 'atomic_number': 101, 'electrons': 101, 'protons': 101, 'atomic_weight': 258},
    102: {'symbol': 'No', 'name': 'Nobelium', 'atomic_number': 102, 'electrons': 102, 'protons': 102, 'atomic_weight': 259},
    103: {'symbol': 'Lr', 'name': 'Lawrencium', 'atomic_number': 103, 'electrons': 103, 'protons': 103, 'atomic_weight': 262},
    104: {'symbol': 'Rf', 'name': 'Rutherfordium', 'atomic_number': 104, 'electrons': 104, 'protons': 104, 'atomic_weight': None},
    105: {'symbol': 'Db', 'name': 'Dubnium', 'atomic_number': 105, 'electrons': 105, 'protons': 105, 'atomic_weight': None},
    106: {'symbol': 'Sg', 'name': 'Seaborgium', 'atomic_number': 106, 'electrons': 106, 'protons': 106, 'atomic_weight': None},
    107: {'symbol': 'Bh', 'name': 'Bohrium', 'atomic_number': 107, 'electrons': 107, 'protons': 107, 'atomic_weight': None},
    108: {'symbol': 'Hs', 'name': 'Hassium', 'atomic_number': 108, 'electrons': 108, 'protons': 108, 'atomic_weight': None},
    109: {'symbol': 'Mt', 'name': 'Meitnerium', 'atomic_number': 109, 'electrons': 109, 'protons': 109, 'atomic_weight': None},
    110: {'symbol': 'Ds', 'name': 'Darmstadtium', 'atomic_number': 110, 'electrons': 110, 'protons': 110, 'atomic_weight': None},
    111: {'symbol': 'Rg', 'name': 'Roentgenium', 'atomic_number': 111, 'electrons': 111, 'protons': 111, 'atomic_weight': None},
    112: {'symbol': 'Cn', 'name': 'Copernicium', 'atomic_number': 112, 'electrons': 112, 'protons': 112, 'atomic_weight': None},
    113: {'symbol': 'Nh', 'name': 'Nihonium', 'atomic_number': 113, 'electrons': 113, 'protons': 113, 'atomic_weight': None},
    114: {'symbol': 'Fl', 'name': 'Flerovium', 'atomic_number': 114, 'electrons': 114, 'protons': 114, 'atomic_weight': None},
    115: {'symbol': 'Mc', 'name': 'Moscovium', 'atomic_number': 115, 'electrons': 115, 'protons': 115, 'atomic_weight': None},
    116: {'symbol': 'Lv', 'name': 'Livermorium', 'atomic_number': 116, 'electrons': 116, 'protons': 116, 'atomic_weight': None},
    117: {'symbol': 'Ts', 'name': 'Tennessine', 'atomic_number': 117, 'electrons': 117, 'protons': 117, 'atomic_weight': None},
    118: {'symbol': 'Og', 'name': 'Oganesson', 'atomic_number': 118, 'electrons': 118, 'protons': 118, 'atomic_weight': None}

}


def details(atomic_number):
    return periodic_table.get(atomic_number)


atomic_number = int(input("\n  Enter the atomic number of the element: \n (1/2/3..../118) :"))


element = details(atomic_number)


if element:
    print(f"Element symbol: {element.get('symbol')}")
    print(f"Element name: {element.get('name')}")
    print(f"Atomic number: {element.get('atomic_number')}")
    print(f"Number of electrons: {element.get('electrons')}")
    print(f"Number of protons: {element.get('protons')}")
    print(f"Atomic weight: {element.get('atomic_weight')}")

else:
    print("Please use the numbers 1, 2, or 3. There are no elements less than 0 or greater than 118.")

